<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { createAgentStartClient } from '../../../client';import { useAgentStartClient } from '../../../client/vue';import { useAgentStartConfig } from '../../../config';
import type { ConnectorConnection, ConnectorDefinition, ConnectorInstallation } from '../../../connector-hub/types';import JsonSchemaForm from '../../../connector-hub/components/JsonSchemaForm.vue';
defineProps<{nodeId?:string}>();const form:any=defineModel();const global=useAgentStartConfig();const client=useAgentStartClient()??createAgentStartClient({baseUrl:global.apiBase??'/api'});const connectors=ref<ConnectorDefinition[]>([]);const installations=ref<ConnectorInstallation[]>([]);const connections=ref<ConnectorConnection[]>([]);const loading=ref(false);const error=ref('');
const connector=computed(()=>connectors.value.find(c=>c.key.provider===form.value.provider&&c.key.connectorId===form.value.connectorId));const action=computed(()=>connector.value?.actions.find(a=>a.id===form.value.actionId));const availableConnections=computed(()=>{const i=installations.value.find(x=>x.provider===form.value.provider&&x.connectorId===form.value.connectorId);return connections.value.filter(c=>c.installationId===i?.id)});
async function load(){loading.value=true;try{[connectors.value,installations.value,connections.value]=await Promise.all([client.connectors.list(),client.connectors.listInstallations(),client.connectors.listConnections()])}catch(e:any){error.value=e?.message??'加载连接器失败'}finally{loading.value=false}}
watch(()=>form.value.connectorId,()=>{if(!connector.value?.actions.some(a=>a.id===form.value.actionId))form.value.actionId='';form.value.connectorName=connector.value?.name??''});watch(()=>form.value.actionId,()=>form.value.actionName=action.value?.name??'');watch(()=>form.value.connectionId,()=>form.value.connectionName=connections.value.find(c=>c.id===form.value.connectionId)?.name??'');onMounted(load);
</script>
<template><div class="cnc"><div v-if="loading">加载连接器…</div><div v-if="error" class="error">{{error}}</div><label>连接器<select v-model="form.connectorId" @change="form.provider=($event.target as HTMLSelectElement).selectedOptions[0]?.dataset.provider||''"><option value="">请选择</option><option v-for="c in connectors" :key="`${c.key.provider}:${c.key.connectorId}`" :value="c.key.connectorId" :data-provider="c.key.provider">{{c.name}}（{{c.key.provider}}）</option></select></label><label>Action<select v-model="form.actionId" :disabled="!connector"><option value="">请选择</option><option v-for="a in connector?.actions||[]" :key="a.id" :value="a.id">{{a.name}} · {{a.riskLevel}}</option></select></label><label>连接配置<select v-model="form.connectionId"><option value="">使用默认连接</option><option v-for="c in availableConnections" :key="c.id" :value="c.id">{{c.name}} · {{c.status}}</option></select></label><section v-if="action"><h4>输入参数</h4><p>{{action.description}}。字符串字段可直接填写 <code v-pre>{{#节点.字段#}}</code> 工作流变量。</p><JsonSchemaForm v-model="form.inputs" :schema="action.inputSchema"/></section><label>输出变量<input v-model="form.outputKey" placeholder="result"/></label><div v-if="action?.riskLevel==='DESTRUCTIVE'" class="warning">高风险操作：运行前请确认权限和目标对象。</div></div></template>
<style scoped>.cnc{display:grid;gap:15px}.cnc label{display:grid;gap:6px;font-size:13px}.cnc select,.cnc input{border:1px solid #d1d5db;border-radius:6px;padding:8px;background:#fff}.cnc section{display:grid;gap:8px}.cnc h4,.cnc p{margin:0}.cnc p{font-size:12px;color:#6b7280}.error{color:#dc2626}.warning{padding:9px;background:#fff7ed;color:#c2410c;border-radius:6px}:global(.dark) .cnc select,:global(.dark) .cnc input{background:#27272a;color:#eee;border-color:#52525b}</style>
