<script setup lang="ts">
import { ref, watch } from 'vue';
import type { AgentStartClient } from '../../client';
import type { ConnectorConnection, ConnectorDefinition, ConnectorInstallation } from '../types';
import JsonSchemaForm from './JsonSchemaForm.vue';
const props=defineProps<{open:boolean;client:AgentStartClient;connector?:ConnectorDefinition;installation?:ConnectorInstallation;connection?:ConnectorConnection;tenantId?:string}>();
const emit=defineEmits<{(e:'update:open',v:boolean):void;(e:'saved'):void}>();
const name=ref('');const credentials=ref<Record<string,unknown>>({});const config=ref<Record<string,unknown>>({});const saving=ref(false);const testing=ref(false);const testMessage=ref('');const error=ref('');
watch(()=>[props.open,props.connection?.id],()=>{name.value=props.connection?.name??`${props.connector?.name??'Connector'} 连接`;credentials.value={};config.value={};error.value='';testMessage.value='';},{immediate:true});
async function save(){if(!props.installation)return; saving.value=true;try{await props.client.connectors.saveConnection({id:props.connection?.id,tenantId:props.tenantId,installationId:props.installation.id,name:name.value,credentials:Object.keys(credentials.value).length?credentials.value:undefined,config:Object.keys(config.value).length?config.value:undefined});emit('saved');emit('update:open',false)}catch(e:any){error.value=e?.message??'保存失败'}finally{saving.value=false}}
async function testConnection(){if(!props.connection)return;testing.value=true;try{const result=await props.client.connectors.testConnection(props.connection.id,props.tenantId);testMessage.value=result.message}catch(e:any){error.value=e?.message??'验证失败'}finally{testing.value=false}}
async function remove(){if(!props.connection||!confirm(`删除连接「${props.connection.name}」？`))return;await props.client.connectors.deleteConnection(props.connection.id,props.tenantId);emit('saved');emit('update:open',false)}
</script>
<template><div v-if="open" class="modal-mask" @click.self="emit('update:open',false)"><section class="modal"><header><b>配置连接 · {{ connector?.name }}</b><button @click="emit('update:open',false)">×</button></header><main><label>连接名称<input v-model="name"/></label><div><h4>凭证</h4><p>已保存的密码不会回显；留空不会覆盖原凭证。</p><JsonSchemaForm v-model="credentials" :schema="connector?.configurationSchema" /></div><div><h4>附加配置（可选）</h4><JsonSchemaForm v-model="config" /></div><p v-if="testMessage" class="success">{{testMessage}}</p><p v-if="error" class="error">{{error}}</p></main><footer><button v-if="connection" class="danger" @click="remove">删除</button><button v-if="connection" :disabled="testing" @click="testConnection">{{testing?'验证中…':'验证已保存配置'}}</button><button @click="emit('update:open',false)">取消</button><button class="primary" :disabled="saving||!name" @click="save">{{saving?'保存中…':'保存连接'}}</button></footer></section></div></template>
<style scoped>.modal-mask{position:fixed;inset:0;background:#0007;display:grid;place-items:center;z-index:1200}.modal{width:min(620px,94vw);max-height:90vh;overflow:auto;background:#fff;border-radius:12px}.modal header,.modal footer{display:flex;justify-content:space-between;align-items:center;padding:16px 20px;border-bottom:1px solid #eee}.modal footer{border:0;border-top:1px solid #eee;justify-content:flex-end;gap:10px}.modal header button{border:0;background:none;font-size:24px}.modal main{padding:18px 20px;display:grid;gap:18px}.modal label{display:grid;gap:7px}.modal input{border:1px solid #d1d5db;border-radius:7px;padding:9px}.modal h4{margin:0}.modal p{color:#6b7280;font-size:12px}.modal button{border:1px solid #d1d5db;background:#fff;border-radius:7px;padding:8px 14px}.modal .primary{background:#4f46e5;color:white;border-color:#4f46e5}.error{color:#dc2626!important}:global(.dark) .modal{background:#18181b;color:#eee}</style>
