<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { createAgentStartClient, type AgentStartClient } from '../../client';
import { useAgentStartClient } from '../../client/vue';
import { mergeAgentStartHeaders, type AgentStartHeaders, useAgentStartConfig } from '../../config';
import type { ConnectorAction, ConnectorConnection, ConnectorDefinition, ConnectorInstallation } from '../types';
import ConnectorActionTestDrawer from './ConnectorActionTestDrawer.vue';
import ConnectorConnectionModal from './ConnectorConnectionModal.vue';
import ConnectorDetailDrawer from './ConnectorDetailDrawer.vue';
import OpenClawPluginPanel from './OpenClawPluginPanel.vue';
const props=withDefaults(defineProps<{apiBase?:string;headers?:AgentStartHeaders;tenantId?:string;client?:AgentStartClient}>(),{tenantId:'default'});
const global=useAgentStartConfig();const injected=useAgentStartClient();const client=props.client??injected??createAgentStartClient({baseUrl:props.apiBase??global.apiBase??'/api',getTenant:()=>props.tenantId,headers:()=>mergeAgentStartHeaders(global.headers,props.headers)});
const tab=ref<'connectors'|'plugins'|'executions'>('connectors');const connectors=ref<ConnectorDefinition[]>([]);const installations=ref<ConnectorInstallation[]>([]);const connections=ref<ConnectorConnection[]>([]);const executions=ref<any[]>([]);const loading=ref(false);const error=ref('');const search=ref('');const source=ref('全部');
const selected=ref<ConnectorDefinition>();const action=ref<ConnectorAction>();const testing=ref(false);const connectionOpen=ref(false);const detailsOpen=ref(false);const editingConnection=ref<ConnectorConnection>();
const installation=computed(()=>installations.value.find(i=>i.provider===selected.value?.key.provider&&i.connectorId===selected.value?.key.connectorId));
const connectorConnections=computed(()=>connections.value.filter(c=>c.installationId===installation.value?.id));
const filtered=computed(()=>connectors.value.filter(c=>(source.value==='全部'||c.key.provider===source.value)&&(!search.value||`${c.name} ${c.description??''} ${c.key.connectorId}`.toLowerCase().includes(search.value.toLowerCase()))));
const sources=computed(()=>['全部',...new Set(connectors.value.map(c=>c.key.provider))]);
async function load(){loading.value=true;error.value='';try{[connectors.value,installations.value,connections.value]=await Promise.all([client.connectors.list(),client.connectors.listInstallations(props.tenantId),client.connectors.listConnections(props.tenantId)]);if(connectors.value.length&&installations.value.length===0)installations.value=await client.connectors.synchronize(props.tenantId)}catch(e:any){error.value=e?.message??'加载失败'}finally{loading.value=false}}
async function refresh(){await client.connectors.refresh();await client.connectors.synchronize(props.tenantId);await load()}
async function toggle(c:ConnectorDefinition){const i=installations.value.find(x=>x.provider===c.key.provider&&x.connectorId===c.key.connectorId);if(!i){await client.connectors.synchronize(props.tenantId);return load()}await client.connectors.setInstallationEnabled(i.id,!i.enabled,props.tenantId);await load()}
async function openConnection(c:ConnectorDefinition,connection?:ConnectorConnection){selected.value=c;editingConnection.value=connection;if(!installations.value.some(i=>i.provider===c.key.provider&&i.connectorId===c.key.connectorId))installations.value=await client.connectors.synchronize(props.tenantId);connectionOpen.value=true}function test(c:ConnectorDefinition,a:ConnectorAction){selected.value=c;action.value=a;testing.value=true}function details(c:ConnectorDefinition){selected.value=c;detailsOpen.value=true}
async function loadExecutions(){try{executions.value=await client.connectors.listExecutions({tenantId:props.tenantId,limit:100})}catch(e:any){error.value=e?.message??'加载审计失败'}}
onMounted(load);
</script>
<template><div class="hub"><header class="hero"><div><h2>Connector 中心</h2><p>统一管理自有连接器与 OpenClaw 插件生态</p></div><button @click="refresh">刷新并同步</button></header><nav><button :class="{active:tab==='connectors'}" @click="tab='connectors'">连接器</button><button :class="{active:tab==='plugins'}" @click="tab='plugins'">OpenClaw 插件</button><button :class="{active:tab==='executions'}" @click="tab='executions';loadExecutions()">执行审计</button></nav><div v-if="error" class="error">{{error}}</div>
<template v-if="tab==='connectors'"><div class="filters"><input v-model="search" placeholder="搜索连接器、描述或 ID"/><select v-model="source"><option v-for="s in sources" :key="s">{{s}}</option></select><span>{{filtered.length}} 个连接器</span></div><div v-if="loading">加载中…</div><div class="grid"><article v-for="c in filtered" :key="`${c.key.provider}:${c.key.connectorId}`"><div class="card-head"><span class="icon">{{c.icon||'🔌'}}</span><div><b>{{c.name}}</b><small>{{c.key.provider}} · {{c.version}}</small></div><span class="state" :class="installations.find(i=>i.provider===c.key.provider&&i.connectorId===c.key.connectorId)?.enabled?'on':'off'">{{installations.find(i=>i.provider===c.key.provider&&i.connectorId===c.key.connectorId)?.enabled?'已启用':'已禁用'}}</span></div><p>{{c.description}}</p><div class="badges"><span>{{c.category||'其他'}}</span><span>{{c.trustLevel||'UNTRUSTED'}}</span><span>{{c.actions.length}} Actions</span></div><div class="action-list"><button v-for="a in c.actions.slice(0,4)" :key="a.id" @click="test(c,a)"><span>{{a.name}}</span><small>{{a.riskLevel||'WRITE'}}</small></button></div><footer><button @click="details(c)">查看详情</button><button @click="openConnection(c)">+ 新建连接</button><button @click="toggle(c)">{{installations.find(i=>i.provider===c.key.provider&&i.connectorId===c.key.connectorId)?.enabled?'禁用':'启用'}}</button></footer></article></div></template>
<OpenClawPluginPanel v-else-if="tab==='plugins'" :client="client" @changed="refresh"/>
<div v-else class="audit"><table><thead><tr><th>时间</th><th>连接器 / Action</th><th>来源</th><th>状态</th><th>耗时</th><th>错误</th></tr></thead><tbody><tr v-for="e in executions" :key="e.id"><td>{{e.createdAt||'-'}}</td><td>{{e.connectorId}} / {{e.actionId}}</td><td>{{e.agentId?'Agent':e.workflowId?'Workflow':'API'}}</td><td>{{e.status}}</td><td>{{e.durationMs??'-'}} ms</td><td>{{e.errorMessage||'-'}}</td></tr></tbody></table></div>
<ConnectorDetailDrawer v-model:open="detailsOpen" :connector="selected" :installation="installation" :connections="connectorConnections" @test="a=>selected&&test(selected,a)" @connection="c=>selected&&openConnection(selected,c)" @toggle="selected&&toggle(selected)"/><ConnectorActionTestDrawer v-model:open="testing" :client="client" :connector="selected" :action="action" :tenant-id="tenantId"/><ConnectorConnectionModal v-model:open="connectionOpen" :client="client" :connector="selected" :installation="installation" :connection="editingConnection" :tenant-id="tenantId" @saved="load"/></div></template>
<style scoped>.hub{color:#111827;display:grid;gap:18px}.hero{display:flex;justify-content:space-between;align-items:center}.hero h2{margin:0}.hero p{margin:5px 0;color:#6b7280}.hero button,nav button,.filters input,.filters select,article button{border:1px solid #d1d5db;background:#fff;border-radius:7px;padding:8px 12px}.hero button{background:#4f46e5;color:white;border-color:#4f46e5}nav{display:flex;border-bottom:1px solid #e5e7eb;gap:4px}nav button{border:0;border-radius:0;background:none}nav .active{color:#4f46e5;border-bottom:2px solid #4f46e5}.filters{display:flex;gap:10px;align-items:center}.filters input{min-width:280px}.filters span{margin-left:auto;color:#6b7280}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:14px}.grid article{border:1px solid #e5e7eb;border-radius:12px;padding:16px;display:grid;gap:13px}.card-head{display:flex;gap:10px;align-items:center}.card-head>div{display:grid;flex:1}.card-head small{color:#6b7280}.icon{font-size:25px}.state{font-size:12px}.on{color:#15803d}.off{color:#6b7280}article p{margin:0;color:#6b7280;min-height:40px}.badges{display:flex;gap:6px}.badges span{font-size:11px;background:#f3f4f6;border-radius:10px;padding:3px 7px}.action-list{display:grid;gap:6px}.action-list button{display:flex;justify-content:space-between;text-align:left}.action-list small{color:#6b7280}article footer{display:flex;justify-content:flex-end;gap:8px;border-top:1px solid #eee;padding-top:12px}.audit{overflow:auto}.audit table{width:100%;border-collapse:collapse}.audit th,.audit td{text-align:left;border-bottom:1px solid #e5e7eb;padding:10px}.error{color:#dc2626}:global(.dark) .hub{color:#eee}:global(.dark) .grid article{border-color:#3f3f46}:global(.dark) .hero button,:global(.dark) article button,:global(.dark) .filters input,:global(.dark) .filters select{background:#27272a;color:#eee;border-color:#52525b}</style>
