<script setup lang="ts">
import { onMounted, ref } from 'vue';
import type { AgentStartClient } from '../../client';
import type { OpenClawPlugin, OpenClawRuntime } from '../types';
import JsonSchemaForm from './JsonSchemaForm.vue';
const props=defineProps<{client:AgentStartClient}>(); const emit=defineEmits<{(e:'changed'):void}>();
const runtime=ref<OpenClawRuntime>();const plugins=ref<OpenClawPlugin[]>([]);const loading=ref(false);const error=ref('');const showInstall=ref(false);const sourceType=ref('npm');const source=ref('');const version=ref('');const configuring=ref<OpenClawPlugin>();const config=ref<Record<string,unknown>>({});
async function load(){loading.value=true;error.value='';try{[runtime.value,plugins.value]=await Promise.all([props.client.connectors.runtime(),props.client.connectors.plugins()])}catch(e:any){error.value=e?.message??'OpenClaw 不可用'}finally{loading.value=false}}
async function install(){await props.client.connectors.installPlugin({sourceType:sourceType.value,source:source.value,version:version.value||undefined});showInstall.value=false;source.value='';await load();emit('changed')}
async function toggle(p:OpenClawPlugin){await props.client.connectors.setPluginEnabled(p.id,!p.enabled);await load();emit('changed')}
async function saveConfig(){if(!configuring.value)return;await props.client.connectors.configurePlugin(configuring.value.id,config.value);configuring.value=undefined;config.value={};await load();emit('changed')}
async function uninstall(p:OpenClawPlugin){if(!confirm(`卸载「${p.name}」？引用其工具的 Agent 和工作流将无法执行。`))return;await props.client.connectors.uninstallPlugin(p.id);await load();emit('changed')}
onMounted(load);defineExpose({load});
</script>
<template><div class="ocp"><div class="runtime"><span :class="['dot',runtime?.status==='UP'?'up':'down']"></span><div><b>OpenClaw {{runtime?.status==='UP'?'已连接':'未连接'}}</b><small>{{runtime?.version||'未知版本'}} · Bridge {{runtime?.bridgeVersion||'-'}}</small></div><button @click="load">刷新</button><button class="primary" @click="showInstall=true">安装插件</button></div><div v-if="error" class="error">{{error}}</div><div v-if="loading">加载中…</div><div class="plugins"><article v-for="p in plugins" :key="p.id"><div><b>{{p.name}}</b><small>{{p.id}} · {{p.version||'-'}}</small><p>{{p.description}}</p></div><span :class="p.enabled?'enabled':'disabled'">{{p.enabled?'已启用':'已禁用'}}</span><div class="actions"><button @click="configuring=p">配置</button><button @click="toggle(p)">{{p.enabled?'禁用':'启用'}}</button><button class="danger" @click="uninstall(p)">卸载</button></div></article></div>
<div v-if="showInstall" class="mask" @click.self="showInstall=false"><section><h3>安装 OpenClaw 插件</h3><label>来源<select v-model="sourceType"><option value="npm">npm</option><option value="clawhub">ClawHub</option></select></label><label>包名或来源<input v-model="source" placeholder="@openclaw/example-plugin"/></label><label>版本<input v-model="version" placeholder="建议固定明确版本"/></label><p>远程安装必须由服务端启用，并受可信包名前缀白名单约束。</p><footer><button @click="showInstall=false">取消</button><button class="primary" :disabled="!source" @click="install">安装</button></footer></section></div>
<div v-if="configuring" class="mask" @click.self="configuring=undefined"><section><h3>配置 {{configuring.name}}</h3><JsonSchemaForm v-model="config" :schema="configuring.configSchema"/><footer><button @click="configuring=undefined">取消</button><button class="primary" @click="saveConfig">保存</button></footer></section></div></div></template>
<style scoped>.ocp{display:grid;gap:16px}.runtime{display:flex;align-items:center;gap:10px;padding:14px;border:1px solid #e5e7eb;border-radius:10px}.runtime div{display:grid;flex:1}.runtime small,article small{color:#6b7280}.dot{width:10px;height:10px;border-radius:50%}.up{background:#22c55e}.down{background:#ef4444}.plugins{display:grid;gap:10px}.plugins article{display:grid;grid-template-columns:1fr auto auto;gap:16px;align-items:center;padding:14px;border:1px solid #e5e7eb;border-radius:10px}.plugins article div:first-child{display:grid;gap:3px}.plugins p{margin:3px 0;color:#6b7280}.actions{display:flex;gap:7px}.enabled{color:#15803d}.disabled{color:#6b7280}button,select,input{border:1px solid #d1d5db;background:#fff;border-radius:7px;padding:7px 11px}.primary{background:#4f46e5;color:#fff;border-color:#4f46e5}.danger{color:#dc2626}.error{color:#dc2626}.mask{position:fixed;inset:0;background:#0007;display:grid;place-items:center;z-index:1200}.mask section{width:min(520px,92vw);background:#fff;border-radius:12px;padding:20px;display:grid;gap:14px}.mask label{display:grid;gap:6px}.mask footer{display:flex;justify-content:flex-end;gap:8px}:global(.dark) .runtime,:global(.dark) article{border-color:#3f3f46}:global(.dark) .mask section{background:#18181b;color:#eee}</style>
